//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVdbEntities : DbContext
    {
        public CVdbEntities()
            : base("name=CVdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CERT> TBL_CERT { get; set; }
        public virtual DbSet<TBL_COM> TBL_COM { get; set; }
        public virtual DbSet<TBL_EDU> TBL_EDU { get; set; }
        public virtual DbSet<TBL_EXP> TBL_EXP { get; set; }
        public virtual DbSet<TBL_HOBIES> TBL_HOBIES { get; set; }
        public virtual DbSet<TBL_SKILLS> TBL_SKILLS { get; set; }
        public virtual DbSet<TBL_SOCIAL> TBL_SOCIAL { get; set; }
    }
}
