//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ABOUT
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public string Mail { get; set; }
        public string Identification { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
    }
}
