//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EDU
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string LowerHeader { get; set; }
        public string Role { get; set; }
        public string GPA { get; set; }
        public string Date { get; set; }
    }
}
